project_id = "eociecgrdwllggcohmko"

[functions.draw]
verify_jwt = true

[functions.auto-draw-scheduler]
verify_jwt = false

[functions.catalog-search]
verify_jwt = false

[functions.catalog-item]
verify_jwt = false

[functions.members-add]
verify_jwt = true
